[package]
name = "saxx"
version = "0.1.0"
authors = ["Yuta Taniguchi <yuta.taniguchi.y.t@gmail.com>"]
description = "Rust bindings to C++ suffix array libraries."
license = "MIT"
repository = "https://github.com/yuttie/saxx"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"
